### ISSUE TITLE
cannot associate floating IP in horizon

### ISSUE THREAD

**Issue by AbelNavarro** [midokura/midonet-openstack#21]
When trying to associate a floating IP from horizon, it always fails.

Steps to reproduce:
1. Create VM
2. Associate IP (dropbox option in instances panel)
3. Allocate new IP
4. Associate

No errors reported in quantum or midolman-mgmt logs.

![Screen Shot 2013-02-26 at 3 54 45 PM](https://f.cloud.github.com/assets/1333236/196680/c8da286a-8024-11e2-9e9b-39a563603a2c.png)

**Comment by adjohn** [comment]
Floating IPs is not supported in Horizon in Folsom, see the doc here under "Known Issues":
http://docs.openstack.org/developer/horizon/releases/2012_2.html

You will need to use the quantum CLI in order to associate floating IPs. Also please do not kill a VM without disassociating the floating IP via quantum first, or you will run into troubles. :)

**Comment by AbelNavarro** [comment]
closing because it's the expected behavior.
